settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: mikrus
    name: niedzwiedzinski.cyou
    url: 'http://niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: ipv4-tunnel
    name: 4.niedzwiedzinski.cyou
    url: 'https://4.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: matus
    name: matus
    url: 'https://jakubmatusewicz.art'
    method: GET
    expectStatus: 200
    
  - id: puszcza
    name: puszcza
    url: 'https://puszcza.netlify.app'
    method: GET
    expectStatus: 200
