settings:
  title: 'Status Page'
  url: 'https://status.niedzwiedzinski.cyou' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: personal
    name: 'personal site'
    url: 'https://niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: matus
    name: 'matus'
    url: 'https://jakubmatusewicz.art'
    method: GET
    expectStatus: 200
    
  - id: pics
    name: 'pics'
    url: 'https://pics.niedzwiedzinski.cyou/mando/'
    method: GET
    expectStatus: 200
    
  - id: cgit
    name: 'cgit'
    url: 'https://git.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200

  - id: cybercoach
    name: 'Cyber Coach'
    url: 'https://cybercoach.pl'
    method: GET
    expectStatus: 200
    
  - id: srv1
    name: 'srv1'
    url: 'https://srv1.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: cgit
    name: 'cgit'
    url: 'https://git.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
