settings:
  title: 'Status Page'
  url: 'https://status.niedzwiedzinski.cyou' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: mikrus
    name: 'personal site'
    url: 'http://niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: ipv4-tunnel
    name: 'IPv4 tunnel for personal site'
    url: 'https://4.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: matus
    name: 'matus'
    url: 'https://jakubmatusewicz.art'
    method: GET
    expectStatus: 200
    
  - id: puszcza
    name: '19pdh-puszcza'
    url: 'https://puszcza.netlify.app'
    method: GET
    expectStatus: 200
    
  - id: pics
    name: 'pics'
    url: 'https://pics.niedzwiedzinski.cyou/mando/'
    method: GET
    expectStatus: 200
    
  - id: low-puszcza-netlify
    name: 'low-puszcza netlify'
    url: 'https://low-puszcza.netlify.app/'
    method: GET
    expectStatus: 200
    
  - id: low-puszcza
    name: 'low-puszcza Github Pages'
    url: 'https://19pdh.github.io/low-puszcza/'
    method: GET
    expectStatus: 200
    
  - id: srv1
    name: 'srv1'
    url: 'https://srv1.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
    
  - id: cgit
    name: 'cgit'
    url: 'https://git.niedzwiedzinski.cyou'
    method: GET
    expectStatus: 200
